import Head from "next/head";
import { GetServerSideProps } from "next";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Apartments from "../components/apartments";
import { getItems } from "./api/getApartments";
import { Property } from "../types/Property";

const inter = Inter({ subsets: ["latin"] });

export default function Home(data: {
    data: { _embedded: { estates: Property[] } };
}) {
    //
    const { estates } = data.data._embedded;
    console.log("qwe", estates);
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                {estates.length > 0 &&
                    estates.map(({ name, _links }) => {
                        console.log("_links", _links.images[0]);
                        return (
                            <li key={name} className={styles.items}>
                                <p>{name}</p>
                                {/* <div>{_links.images[]}</div> */}
                            </li>
                        );
                    })}
                {/* <Apartments data={estates} /> */}
            </main>
        </>
    );
}
export const getServerSideProps: GetServerSideProps = async () => {
    const { data } = await getItems("1", "5");
    // const { estates } = data;
    // .data._embedded.estates;
    return { props: { data: data } };
};
